<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

	<!-- design-time assets (workaround) -->
	<ItemGroup>
		<None Remove="Assets\Background - Copy.svg" />
		<None Remove="Assets\PuckOff - Copy.svg" />
		<None Remove="Assets\PuckOn - Copy.svg" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="Assets\Background - Copy.svg">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\PuckOff - Copy.svg">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\PuckOn - Copy.svg">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<!-- runtime assets -->
	<ItemGroup>
		<Resource Include="Assets\Background.svg" />
		<Resource Include="Assets\PuckOff.svg" />
		<Resource Include="Assets\PuckOn.svg" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.1.2" />
    <PackageReference Include="SharpVectors" Version="1.8.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CrapsLibrary\CrapsLibrary.csproj" />
  </ItemGroup>

</Project>
